// NIECP Government Integration Registry
// Truthful registry of government providers/channels. URLs are verified
// official portals only. Nothing here is marked LIVE — no authorized
// government API credentials exist for this application.

export const GOVERNMENT_REGISTRY = [
  {
    provider_name: "NSWS",
    service_name: "National Single Window System",
    jurisdiction: "India (Central + participating States)",
    authority: "Invest India / DPIIT",
    official_portal_url: "https://www.nsws.gov.in/",
    api_directory_url: "https://www.nsws.gov.in/",
    api_specification_url: "",
    environment: "OFFICIAL_REDIRECT",
    authorization_status: "PENDING",
    supported_operations: [],
    authentication_method: "OAuth 2.0 (not configured)",
    schema_version: "not connected",
    last_verified_at: "2026-09-22",
    fallback_mode: "OFFICIAL_REDIRECT",
    data_categories: ["Project profile", "Application draft"],
    consent_required: true,
    live: false,
    source_type: "VERIFIED_OFFICIAL",
    verification_status: "VERIFIED",
    capabilities: ["Official portal redirect", "Application preparation", "Manual tracking"],
    disclosure: "Live API not connected. Authorization pending."
  },
  {
    provider_name: "Tamil Nadu Single Window",
    service_name: "Tamil Nadu Single Window Portal (TNSWP)",
    jurisdiction: "Tamil Nadu",
    authority: "Guidance Tamil Nadu / State Departments",
    official_portal_url: "https://tnswp.com/",
    api_directory_url: "https://tnswp.com/",
    api_specification_url: "",
    environment: "OFFICIAL_REDIRECT",
    authorization_status: "PENDING",
    supported_operations: [],
    authentication_method: "OAuth 2.0 (not configured)",
    schema_version: "not connected",
    last_verified_at: "2026-09-22",
    fallback_mode: "OFFICIAL_REDIRECT",
    data_categories: ["Project profile", "Application draft"],
    consent_required: true,
    live: false,
    source_type: "VERIFIED_OFFICIAL",
    verification_status: "VERIFIED",
    capabilities: ["Official portal redirect", "Application preparation", "Manual tracking"],
    disclosure: "Live API not connected. Authorization pending."
  },
  {
    provider_name: "UDYAM / MSME Dataset",
    service_name: "List of MSME Registered Units under UDYAM (data.gov.in)",
    jurisdiction: "India (Central)",
    authority: "Ministry of Micro, Small and Medium Enterprises",
    official_portal_url: "https://udyamregistration.gov.in/",
    api_directory_url: "https://www.data.gov.in/resource/list-msme-registered-units-under-udyam",
    api_specification_url: "https://www.data.gov.in/resource/list-msme-registered-units-under-udyam",
    environment: "PENDING_AUTHORIZATION",
    authorization_status: "PENDING",
    supported_operations: ["dataset_search"],
    authentication_method: "data.gov.in API key (server-side secret)",
    schema_version: "data.gov.in resource API",
    last_verified_at: "2026-09-23",
    fallback_mode: "MANUAL",
    data_categories: ["Public MSME dataset records"],
    consent_required: true,
    live: false,
    source_type: "OFFICIAL_DOCUMENT_KNOWLEDGE",
    verification_status: "PENDING",
    capabilities: ["MSME dataset match", "Project profile enrichment"],
    disclosure: "GOVERNMENT_DATASET_MATCH only — not a UDYAM registration verification. LIVE only after a real authenticated data.gov.in response."
  },
  {
    provider_name: "India Post Pincode Directory",
    service_name: "All India Pincode Directory till last month (data.gov.in)",
    jurisdiction: "India (Central)",
    authority: "Department of Posts",
    official_portal_url: "https://www.indiapost.gov.in/vas/pages/findpincode.aspx",
    api_directory_url: "https://www.data.gov.in/resource/all-india-pincode-directory-till-last-month",
    api_specification_url: "https://www.data.gov.in/resource/all-india-pincode-directory-till-last-month",
    environment: "PENDING_AUTHORIZATION",
    authorization_status: "PENDING",
    supported_operations: ["pincode_lookup"],
    authentication_method: "data.gov.in API key (server-side secret)",
    schema_version: "data.gov.in resource API",
    last_verified_at: "2026-09-23",
    fallback_mode: "MANUAL",
    data_categories: ["Pincode, state, district, post office"],
    consent_required: false,
    live: false,
    source_type: "OFFICIAL_DOCUMENT_KNOWLEDGE",
    verification_status: "PENDING",
    capabilities: ["Pincode validation", "Location enrichment"],
    disclosure: "LIVE only after a real authenticated data.gov.in response."
  },
  {
    provider_name: "MCA Company Master Data",
    service_name: "Company identity intelligence (Ministry of Corporate Affairs)",
    jurisdiction: "India (Central)",
    authority: "Ministry of Corporate Affairs",
    official_portal_url: "https://www.mca.gov.in/",
    api_directory_url: "https://www.mca.gov.in/",
    api_specification_url: "",
    environment: "NOT_AVAILABLE",
    authorization_status: "PENDING",
    supported_operations: [],
    authentication_method: "No authorized MCA API configured",
    schema_version: "not connected",
    last_verified_at: "2026-09-23",
    fallback_mode: "MANUAL",
    data_categories: ["Company identity data"],
    consent_required: true,
    live: false,
    source_type: "OFFICIAL_REDIRECT",
    verification_status: "PENDING",
    capabilities: ["Company search once an authorized API exists"],
    disclosure: "No authorized MCA API is configured. Status: NOT_AVAILABLE — use the official MCA portal."
  },
  {
    provider_name: "DigiLocker (Requester)",
    service_name: "Authorized verified digital document retrieval",
    jurisdiction: "India (Central)",
    authority: "NeGD / MeitY",
    official_portal_url: "https://www.digilocker.gov.in/",
    api_directory_url: "https://apisetu.gov.in/",
    api_specification_url: "https://apisetu.gov.in/",
    environment: "PENDING_AUTHORIZATION",
    authorization_status: "PENDING",
    supported_operations: [],
    authentication_method: "OAuth 2.0 requester flow (partner credentials not authorized)",
    schema_version: "not connected",
    last_verified_at: "2026-09-23",
    fallback_mode: "OFFICIAL_REDIRECT",
    data_categories: ["User-authorized digital documents"],
    consent_required: true,
    live: false,
    source_type: "OFFICIAL_REDIRECT",
    verification_status: "PENDING",
    capabilities: ["Verified document retrieval (after authorization)"],
    disclosure: "DigiLocker integration is awaiting official partner authorization. No fake DigiLocker calls are made."
  },
  {
    provider_name: "API Setu",
    service_name: "API Setu — Government of India API platform",
    jurisdiction: "India (Central)",
    authority: "MeitY / NeGD",
    official_portal_url: "https://apisetu.gov.in/",
    api_directory_url: "https://apisetu.gov.in/",
    api_specification_url: "",
    environment: "NOT_AVAILABLE",
    authorization_status: "NOT_AUTHORIZED",
    supported_operations: [],
    authentication_method: "API key / OAuth (not configured)",
    schema_version: "not connected",
    last_verified_at: "2026-09-22",
    fallback_mode: "OFFICIAL_REDIRECT",
    data_categories: ["Application data"],
    consent_required: true,
    live: false,
    source_type: "VERIFIED_OFFICIAL",
    verification_status: "VERIFIED",
    capabilities: ["Future authorized API routing"],
    disclosure: "API directory is public, but no API is authorized for this application yet."
  },
  {
    provider_name: "NIECP Demo Government",
    service_name: "NIECP Internal Demonstration Environment",
    jurisdiction: "NIECP demonstration only",
    authority: "NIECP-AI (synthetic — no government authority)",
    official_portal_url: "",
    api_directory_url: "",
    api_specification_url: "",
    environment: "DEMO",
    authorization_status: "NOT_AUTHORIZED",
    supported_operations: ["submit", "status", "queries", "response", "documents", "catalog"],
    authentication_method: "None (internal simulation)",
    schema_version: "niecp-demo-v1",
    last_verified_at: "2026-09-22",
    fallback_mode: "DEMO",
    data_categories: ["Synthetic application data"],
    consent_required: true,
    live: false,
    source_type: "DEMO",
    verification_status: "DEMO",
    capabilities: ["Demo submission", "Simulated status updates", "Synthetic queries", "Simulated approval"],
    disclosure: "Demonstration workflow only. Not connected to a live government system. All data is synthetic."
  }
];

export function listProviders() {
  return GOVERNMENT_REGISTRY;
}

export function getProvider(providerName) {
  return GOVERNMENT_REGISTRY.find((p) => p.provider_name === providerName) || null;
}